# Site settings
title: Jeroen Reijn
subtitle: "On Java and software development"
author: Jeroen Reijn
email:
description: "Jeroen Reijn on Java and software development"
disclaimer: "The opinions expressed here are entirely my own and do not reflect the opinion of my employer or that of the Apache Software Foundation."
copyright: "© Jeroen Reijn • All rights reserved."
baseurl: ""
url: "http://blog.jeroenreijn.com"
atom_path: "atom.xml"

# Build settings
markdown: redcarpet
permalink: :year/:month/:title.html

paginate: 5

username: jreijn
disqus_short_name: blogjeroenreijn

sitemap:
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feeds/posts/default"

gems:
  - jekyll-sitemap
