baseURL="https://www.jeroenreijn.com"
languageCode="en-us"
title="Build with Jeroen"
theme="hugo-theme-stack"
ignoreLogs = ['warning-goldmark-raw-html']
titleCaseStyle = 'none'
uglyURLs = true
googleAnalytics= 'G-X0632M0DP7'
